/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MemoryIdRouteImport } from './routes/memory.$id'
import { Route as ApiMemoryGenerateRouteImport } from './routes/api/memory/generate'
import { Route as ApiMemoryQuoteRouteImport } from './routes/api/memory/quote'
import { Route as ApiMemoryStatusTaskIdRouteImport } from './routes/api/memory/status.$taskId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryIdRoute = MemoryIdRouteImport.update({
  id: '/memory/$id',
  path: '/memory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryGenerateRoute = ApiMemoryGenerateRouteImport.update({
  id: '/api/memory/generate',
  path: '/api/memory/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryQuoteRoute = ApiMemoryQuoteRouteImport.update({
  id: '/api/memory/quote',
  path: '/api/memory/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMemoryStatusTaskIdRoute = ApiMemoryStatusTaskIdRouteImport.update({
  id: '/api/memory/status/$taskId',
  path: '/api/memory/status/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/diary': typeof DiaryRoute
  '/profile': typeof ProfileRoute
  '/memory/$id': typeof MemoryIdRoute
  '/api/memory/generate': typeof ApiMemoryGenerateRoute
  '/api/memory/quote': typeof ApiMemoryQuoteRoute
  '/api/memory/status/$taskId': typeof ApiMemoryStatusTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/diary': typeof DiaryRoute
  '/profile': typeof ProfileRoute
  '/memory/$id': typeof MemoryIdRoute
  '/api/memory/generate': typeof ApiMemoryGenerateRoute
  '/api/memory/quote': typeof ApiMemoryQuoteRoute
  '/api/memory/status/$taskId': typeof ApiMemoryStatusTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/diary': typeof DiaryRoute
  '/profile': typeof ProfileRoute
  '/memory/$id': typeof MemoryIdRoute
  '/api/memory/generate': typeof ApiMemoryGenerateRoute
  '/api/memory/quote': typeof ApiMemoryQuoteRoute
  '/api/memory/status/$taskId': typeof ApiMemoryStatusTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/diary'
    | '/profile'
    | '/memory/$id'
    | '/api/memory/generate'
    | '/api/memory/quote'
    | '/api/memory/status/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/diary'
    | '/profile'
    | '/memory/$id'
    | '/api/memory/generate'
    | '/api/memory/quote'
    | '/api/memory/status/$taskId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/diary'
    | '/profile'
    | '/memory/$id'
    | '/api/memory/generate'
    | '/api/memory/quote'
    | '/api/memory/status/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  DiaryRoute: typeof DiaryRoute
  ProfileRoute: typeof ProfileRoute
  MemoryIdRoute: typeof MemoryIdRoute
  ApiMemoryGenerateRoute: typeof ApiMemoryGenerateRoute
  ApiMemoryQuoteRoute: typeof ApiMemoryQuoteRoute
  ApiMemoryStatusTaskIdRoute: typeof ApiMemoryStatusTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory/$id': {
      id: '/memory/$id'
      path: '/memory/$id'
      fullPath: '/memory/$id'
      preLoaderRoute: typeof MemoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/generate': {
      id: '/api/memory/generate'
      path: '/api/memory/generate'
      fullPath: '/api/memory/generate'
      preLoaderRoute: typeof ApiMemoryGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/quote': {
      id: '/api/memory/quote'
      path: '/api/memory/quote'
      fullPath: '/api/memory/quote'
      preLoaderRoute: typeof ApiMemoryQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memory/status/$taskId': {
      id: '/api/memory/status/$taskId'
      path: '/api/memory/status/$taskId'
      fullPath: '/api/memory/status/$taskId'
      preLoaderRoute: typeof ApiMemoryStatusTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  DiaryRoute: DiaryRoute,
  ProfileRoute: ProfileRoute,
  MemoryIdRoute: MemoryIdRoute,
  ApiMemoryGenerateRoute: ApiMemoryGenerateRoute,
  ApiMemoryQuoteRoute: ApiMemoryQuoteRoute,
  ApiMemoryStatusTaskIdRoute: ApiMemoryStatusTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
